sudo: required
services:
  - docker
env:
  - version=1.1
install: npm install
script: 
  - docker login -u $docker_hub_username -p $docker_hub_password
  - docker build -f docker1/Dockerfile docker1 -t shaohua1990/docker1:${version}
deploy:
  - docker push shaohua1990/docker1:$(version) 